name: Deploy to AWS CodeDeploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Package and deploy
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Register GitHub revision with CodeDeploy
        env:
          APPLICATION_NAME: ${{ vars.CODEDEPLOY_APPLICATION }}
          DEPLOYMENT_GROUP: ${{ vars.CODEDEPLOY_DEPLOYMENT_GROUP }}
        run: |
          # Build a revision JSON pointing to the current repo and commit
          REVISION_JSON=$(jq -n \
            --arg repo "$GITHUB_REPOSITORY" \
            --arg commit "$GITHUB_SHA" \
            '{revisionType: "GitHub", gitHubLocation: {repository: $repo, commitId: $commit}}')
          echo "$REVISION_JSON" > revision.json
          aws deploy create-deployment --application-name "$APPLICATION_NAME" --deployment-group-name "$DEPLOYMENT_GROUP" --revision file://revision.json
